### ISSUE TITLE
How can use this shiro integration with spring in vaadin?

### ISSUE THREAD

**Issue by bonifacechacha** [alejandro-du/shiro-vaadin-integration#2]

**Comment by bonifacechacha** [comment]
Say I have a spring boot application with vaadin 10. How can I configure shiro security incase I dont want to use spring security especially the ShiroFilter?

**Comment by ajilling** [comment]
I'll echo that - it would be nice to have a little more info about how to get this up and running for those not already familiar with Shiro. You mention configuring the ShiroListener and ShiroFilter, but how exactly?

**Comment by invader35** [comment]
To use this with SpringBoot you have to use the WebConfig class provided by the example. (Modified for your purposes and add the @ServletComponentScan annotation to your SpringBoot application class

**Comment by alejandro-du** [comment]
Let's use the forum for this kind of questions. I'll close this issue for now. Cheers.
